apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-block-pvc
  namespace: kbench-pod-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wcp-policy
